# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170721_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='quoteCount',
            field=models.IntegerField(null=True),
        ),
    ]
