# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170721_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='quoteCount',
            field=models.IntegerField(default=0),
        ),
    ]
