# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170721_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='quotes_wall',
        ),
        migrations.AddField(
            model_name='quote',
            name='uFavQs',
            field=models.ManyToManyField(blank=True, related_name='favQs', to='main.User'),
        ),
    ]
