# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170722_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='favQuotes',
        ),
        migrations.AddField(
            model_name='quote',
            name='user_favs',
            field=models.ManyToManyField(blank=True, related_name='fav_quotes', to='main.User'),
        ),
    ]
