# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-19 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0002_user_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_wall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_wall', to='dash_app.User'),
        ),
    ]
